note
	description: "Generate missing Eiffel tasks report by comparing API with database"
	author: "Larry Rix"

class
	REPORT_GENERATOR

create
	make

feature {NONE} -- Initialization

	make
			-- Generate missing tasks report.
		local
			rosetta: SIMPLE_ROSETTA
			client: ROSETTA_CLIENT
			all_tasks: ARRAYED_LIST [ROSETTA_TASK]
			eiffel_tasks: ARRAYED_LIST [ROSETTA_TASK]
			missing: ARRAYED_LIST [STRING]
			file: PLAIN_TEXT_FILE
			i: INTEGER
			task: ROSETTA_TASK
			eiffel_names: HASH_TABLE [BOOLEAN, STRING]
		do
			print ("=== Eiffel Missing Tasks Report Generator ===%N%N")

			-- Get Eiffel tasks from database
			create rosetta.make_with_db ("eiffel_scan.db")
			eiffel_tasks := rosetta.tasks_with_eiffel
			print ("Database has " + eiffel_tasks.count.out + " tasks with Eiffel%N")

			-- Build lookup table
			create eiffel_names.make (eiffel_tasks.count)
			from i := 1 until i > eiffel_tasks.count loop
				eiffel_names.put (True, eiffel_tasks.i_th (i).name)
				i := i + 1
			end

			-- Fetch all tasks from API
			print ("Fetching all tasks from Rosetta Code API...%N")
			create client.make
			all_tasks := client.fetch_all_task_names

			if client.has_error then
				print ("ERROR: " + client.last_error + "%N")
			else
				print ("API returned " + all_tasks.count.out + " total tasks%N")

				-- Find missing
				create missing.make (1200)
				from i := 1 until i > all_tasks.count loop
					if not eiffel_names.has (all_tasks.i_th (i).name) then
						missing.extend (all_tasks.i_th (i).name)
					end
					i := i + 1
				end

				print ("Found " + missing.count.out + " tasks without Eiffel%N%N")

				-- Generate markdown report
				create file.make_create_read_write ("MISSING_EIFFEL_TASKS.md")

				file.put_string ("# Rosetta Code Tasks Missing Eiffel Solutions%N%N")
				file.put_string ("Generated: " + (create {SIMPLE_DATE_TIME}.make_now).out + "%N%N")
				file.put_string ("## Summary%N%N")
				file.put_string ("- **Total tasks on Rosetta Code:** " + all_tasks.count.out + "%N")
				file.put_string ("- **Tasks with Eiffel:** " + eiffel_tasks.count.out + " (" + ((eiffel_tasks.count * 100) // all_tasks.count).out + "%%)%N")
				file.put_string ("- **Tasks without Eiffel:** " + missing.count.out + "%N%N")
				file.put_string ("## Opportunities for Eiffel Contributions%N%N")
				file.put_string ("These are Rosetta Code tasks that do not yet have Eiffel solutions.%N")
				file.put_string ("Contributing solutions helps showcase Eiffel to the programming community.%N%N")
				file.put_string ("### Full List (Alphabetical)%N%N")
				file.put_string ("| # | Task Name | Rosetta Code Link |%N")
				file.put_string ("|---|-----------|-------------------|%N")

				from i := 1 until i > missing.count loop
					file.put_string ("| ")
					file.put_integer (i)
					file.put_string (" | ")
					file.put_string (missing.i_th (i))
					file.put_string (" | [View](https://rosettacode.org/wiki/")
					file.put_string (url_encode (missing.i_th (i)))
					file.put_string (") |%N")
					i := i + 1
				end

				file.put_string ("%N----%N%N")
				file.put_string ("*Report generated by simple_rosetta*%N")
				file.close

				print ("Report written to: MISSING_EIFFEL_TASKS.md%N")
			end

			rosetta.close
		end

feature {NONE} -- Helpers

	url_encode (s: STRING): STRING
			-- URL encode a string for wiki links.
		do
			Result := s.twin
			Result.replace_substring_all (" ", "_")
		end

end
